name: Build

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          -
            mariadb-version: 10.6
            mariadb-package-version: 10.6.14-r0
            mariadb-alpine-image: alpine:3.17.5
          -
            mariadb-version: 10.11
            mariadb-package-version: 10.11.4-r0
            mariadb-alpine-image: alpine:3.18.3
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build ${{ matrix.mariadb-version }}
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          build-args: |
            BUILD_ALPINE_IMAGE=${{ matrix.mariadb-alpine-image }}
            BUILD_MARIADB_PACKAGE_VERSION=${{ matrix.mariadb-package-version }}
          push: true
          tags: aerzas/mariadb:${{ matrix.mariadb-version }}-latest,aerzas/mariadb:${{ matrix.mariadb-version }}-${{ github.ref_name }}
